# Development environment specific properties
spring:
  # PostgreSQL database configuration for development
  datasource:
    url: jdbc:postgresql://localhost:5432/terran_library_dev
    username: terrandb
    password: terrandb
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    entity-packages: com.terran.library.model
    # Hibernate properties for development
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging configuration for development
logging:
  level:
    root: INFO
    com.terran.library: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator configuration for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always